### ISSUE TITLE
Ensure that labview indicators correspond to received state string rather than sent state string

### ISSUE THREAD

**Issue by JonBees** [JonBees/ArduinoFlightSoftware#51]
We need to make sure that the indicators behave correctly during a softkill/abort/fuel dump/etc.

**Comment by JonBees** [comment]
This is important mainly for the items on the P&ID, on which the colors should represent the actual states of the valves for glanceability rather than the commands being sent (these may be different during a soft/hardkill).

**Comment by LunarLionGNC** [comment]
Under Hardkill or Softkill, all valve indicators are greyed out to show that their states on LabView do not represent the craft states. However, these valves can still be clicked on for actuation in case it is necessary to do so.

**Comment by JonBees** [comment]
^^ This is functionally similar enough. We may revisit this later, but for the time being we can leave it as-is.
