### ISSUE TITLE
On Arduino/Xbee disconnect, labview gives up

### ISSUE THREAD

**Issue by JonBees** [JonBees/ArduinoFlightSoftware#6]
Whenever communication to Ground Control is interrupted, LabView stops trying to connect and send/receive packets.

**Comment by JonBees** [comment]
Probably an issue with LabView itself, as stopping and starting the code again has no effect - LabView needs to be totally restarted.

**Comment by LunarLionGNC** [comment]
LabView will now automatically re-connect to the Ground Control Arduino: the user must ensure the Arduino is plugged in and then abort and re-run the LabView interface. This method was tested with an active with the craft as well and it does work in that circumstance.
